name: RevelationLobby
main: main.Lobby
version: 1.0
api-version: 1.13
commands:
  gamemode:
    aliases:
      - gm
    permission-message: "&cNo."
    permission: lobby.gamemode
  holo:
    aliases:
      - hologram
      - hd
    permission-message: "&cNo"
    permission: lobby.holograms